export const SAMPLE_DIR = {
    name: "root",
    type: "folder",
    children: [
        {
            name: "glioma_tumor",
            type: "folder",
            children: [
                { name: "NPX-001.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-001.jpg" },
                { name: "NPX-002.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-002.jpg" },
                { name: "NPX-003.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-003.jpg" },
                { name: "NPX-004.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-004.jpg" },
                { name: "NPX-005.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-005.jpg" },
                { name: "NPX-006.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-006.jpg" },
                { name: "NPX-007.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-007.jpg" },
                { name: "NPX-008.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-008.jpg" },
                { name: "NPX-009.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-009.jpg" },
                { name: "NPX-010.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-010.jpg" },
                { name: "NPX-011.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-011.jpg" },
                { name: "NPX-012.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-012.jpg" },
                { name: "NPX-013.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-013.jpg" },
                { name: "NPX-014.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-014.jpg" },
                { name: "NPX-015.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-015.jpg" },
                { name: "NPX-016.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-016.jpg" },
                { name: "NPX-017.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-017.jpg" },
                { name: "NPX-018.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-018.jpg" },
                { name: "NPX-019.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-019.jpg" },
                { name: "NPX-020.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-020.jpg" },
                { name: "NPX-021.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-021.jpg" },
                { name: "NPX-022.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-022.jpg" },
                { name: "NPX-023.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-023.jpg" },
                { name: "NPX-024.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-024.jpg" },
                { name: "NPX-025.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-025.jpg" },
                { name: "NPX-026.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-026.jpg" },
                { name: "NPX-027.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-027.jpg" },
                { name: "NPX-028.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-028.jpg" },
                { name: "NPX-029.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-029.jpg" },
                { name: "NPX-030.jpg", type: "file", path: "assets/samples/glioma_tumor/NPX-030.jpg" }
            ]
        },
        {
            name: "healthy_control",
            type: "folder",
            children: [
                { name: "NPX-001.jpg", type: "file", path: "assets/samples/healthy_control/NPX-001.jpg" },
                { name: "NPX-002.jpg", type: "file", path: "assets/samples/healthy_control/NPX-002.jpg" },
                { name: "NPX-003.jpg", type: "file", path: "assets/samples/healthy_control/NPX-003.jpg" },
                { name: "NPX-004.jpg", type: "file", path: "assets/samples/healthy_control/NPX-004.jpg" },
                { name: "NPX-005.jpg", type: "file", path: "assets/samples/healthy_control/NPX-005.jpg" },
                { name: "NPX-006.jpg", type: "file", path: "assets/samples/healthy_control/NPX-006.jpg" },
                { name: "NPX-007.jpg", type: "file", path: "assets/samples/healthy_control/NPX-007.jpg" },
                { name: "NPX-008.jpg", type: "file", path: "assets/samples/healthy_control/NPX-008.jpg" },
                { name: "NPX-009.jpg", type: "file", path: "assets/samples/healthy_control/NPX-009.jpg" },
                { name: "NPX-010.jpg", type: "file", path: "assets/samples/healthy_control/NPX-010.jpg" },
                { name: "NPX-011.jpg", type: "file", path: "assets/samples/healthy_control/NPX-011.jpg" },
                { name: "NPX-012.jpg", type: "file", path: "assets/samples/healthy_control/NPX-012.jpg" },
                { name: "NPX-013.jpg", type: "file", path: "assets/samples/healthy_control/NPX-013.jpg" },
                { name: "NPX-014.jpg", type: "file", path: "assets/samples/healthy_control/NPX-014.jpg" },
                { name: "NPX-015.jpg", type: "file", path: "assets/samples/healthy_control/NPX-015.jpg" },
                { name: "NPX-016.jpg", type: "file", path: "assets/samples/healthy_control/NPX-016.jpg" },
                { name: "NPX-017.jpg", type: "file", path: "assets/samples/healthy_control/NPX-017.jpg" },
                { name: "NPX-018.jpg", type: "file", path: "assets/samples/healthy_control/NPX-018.jpg" },
                { name: "NPX-019.jpg", type: "file", path: "assets/samples/healthy_control/NPX-019.jpg" },
                { name: "NPX-020.jpg", type: "file", path: "assets/samples/healthy_control/NPX-020.jpg" },
                { name: "NPX-021.jpg", type: "file", path: "assets/samples/healthy_control/NPX-021.jpg" },
                { name: "NPX-022.jpg", type: "file", path: "assets/samples/healthy_control/NPX-022.jpg" },
                { name: "NPX-023.jpg", type: "file", path: "assets/samples/healthy_control/NPX-023.jpg" },
                { name: "NPX-024.jpg", type: "file", path: "assets/samples/healthy_control/NPX-024.jpg" },
                { name: "NPX-025.jpg", type: "file", path: "assets/samples/healthy_control/NPX-025.jpg" },
                { name: "NPX-026.jpg", type: "file", path: "assets/samples/healthy_control/NPX-026.jpg" },
                { name: "NPX-027.jpg", type: "file", path: "assets/samples/healthy_control/NPX-027.jpg" },
                { name: "NPX-028.jpg", type: "file", path: "assets/samples/healthy_control/NPX-028.jpg" },
                { name: "NPX-029.jpg", type: "file", path: "assets/samples/healthy_control/NPX-029.jpg" },
                { name: "NPX-030.jpg", type: "file", path: "assets/samples/healthy_control/NPX-030.jpg" }
            ]
        },
        {
            name: "meningioma_tumor",
            type: "folder",
            children: [
                { name: "NPX-001.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-001.jpg" },
                { name: "NPX-002.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-002.jpg" },
                { name: "NPX-003.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-003.jpg" },
                { name: "NPX-004.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-004.jpg" },
                { name: "NPX-005.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-005.jpg" },
                { name: "NPX-006.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-006.jpg" },
                { name: "NPX-007.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-007.jpg" },
                { name: "NPX-008.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-008.jpg" },
                { name: "NPX-009.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-009.jpg" },
                { name: "NPX-010.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-010.jpg" },
                { name: "NPX-011.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-011.jpg" },
                { name: "NPX-012.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-012.jpg" },
                { name: "NPX-013.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-013.jpg" },
                { name: "NPX-014.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-014.jpg" },
                { name: "NPX-015.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-015.jpg" },
                { name: "NPX-016.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-016.jpg" },
                { name: "NPX-017.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-017.jpg" },
                { name: "NPX-018.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-018.jpg" },
                { name: "NPX-019.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-019.jpg" },
                { name: "NPX-020.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-020.jpg" },
                { name: "NPX-021.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-021.jpg" },
                { name: "NPX-022.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-022.jpg" },
                { name: "NPX-023.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-023.jpg" },
                { name: "NPX-024.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-024.jpg" },
                { name: "NPX-025.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-025.jpg" },
                { name: "NPX-026.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-026.jpg" },
                { name: "NPX-027.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-027.jpg" },
                { name: "NPX-028.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-028.jpg" },
                { name: "NPX-029.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-029.jpg" },
                { name: "NPX-030.jpg", type: "file", path: "assets/samples/meningioma_tumor/NPX-030.jpg" }
            ]
        },
        {
            name: "pituitary_tumor",
            type: "folder",
            children: [
                { name: "NPX-001.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-001.jpg" },
                { name: "NPX-002.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-002.jpg" },
                { name: "NPX-003.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-003.jpg" },
                { name: "NPX-004.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-004.jpg" },
                { name: "NPX-005.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-005.jpg" },
                { name: "NPX-006.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-006.jpg" },
                { name: "NPX-007.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-007.jpg" },
                { name: "NPX-008.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-008.jpg" },
                { name: "NPX-009.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-009.jpg" },
                { name: "NPX-010.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-010.jpg" },
                { name: "NPX-011.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-011.jpg" },
                { name: "NPX-012.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-012.jpg" },
                { name: "NPX-013.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-013.jpg" },
                { name: "NPX-014.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-014.jpg" },
                { name: "NPX-015.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-015.jpg" },
                { name: "NPX-016.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-016.jpg" },
                { name: "NPX-017.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-017.jpg" },
                { name: "NPX-018.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-018.jpg" },
                { name: "NPX-019.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-019.jpg" },
                { name: "NPX-020.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-020.jpg" },
                { name: "NPX-021.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-021.jpg" },
                { name: "NPX-022.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-022.jpg" },
                { name: "NPX-023.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-023.jpg" },
                { name: "NPX-024.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-024.jpg" },
                { name: "NPX-025.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-025.jpg" },
                { name: "NPX-026.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-026.jpg" },
                { name: "NPX-027.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-027.jpg" },
                { name: "NPX-028.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-028.jpg" },
                { name: "NPX-029.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-029.jpg" },
                { name: "NPX-030.jpg", type: "file", path: "assets/samples/pituitary_tumor/NPX-030.jpg" }
            ]
        }
    ]
};
