export const SAMPLE_DIR = {
    name: "root",
    type: "folder",
    children: [
        {
            name: "Glioma Tumor",
            type: "folder",
            children: [
                { name: "NPX-001.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-001.jpg" },
                { name: "NPX-002.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-002.jpg" },
                { name: "NPX-003.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-003.jpg" },
                { name: "NPX-004.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-004.jpg" },
                { name: "NPX-005.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-005.jpg" },
                { name: "NPX-006.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-006.jpg" },
                { name: "NPX-007.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-007.jpg" },
                { name: "NPX-008.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-008.jpg" },
                { name: "NPX-009.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-009.jpg" },
                { name: "NPX-010.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-010.jpg" },
                { name: "NPX-011.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-011.jpg" },
                { name: "NPX-012.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-012.jpg" },
                { name: "NPX-013.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-013.jpg" },
                { name: "NPX-014.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-014.jpg" },
                { name: "NPX-015.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-015.jpg" },
                { name: "NPX-016.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-016.jpg" },
                { name: "NPX-017.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-017.jpg" },
                { name: "NPX-018.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-018.jpg" },
                { name: "NPX-019.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-019.jpg" },
                { name: "NPX-020.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-020.jpg" },
                { name: "NPX-021.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-021.jpg" },
                { name: "NPX-022.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-022.jpg" },
                { name: "NPX-023.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-023.jpg" },
                { name: "NPX-024.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-024.jpg" },
                { name: "NPX-025.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-025.jpg" },
                { name: "NPX-026.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-026.jpg" },
                { name: "NPX-027.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-027.jpg" },
                { name: "NPX-028.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-028.jpg" },
                { name: "NPX-029.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-029.jpg" },
                { name: "NPX-030.jpg", type: "file", path: "assets/samples/Glioma Tumor/NPX-030.jpg" }
            ]
        },
        {
            name: "Healthy Control",
            type: "folder",
            children: [
                { name: "NPX-001.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-001.jpg" },
                { name: "NPX-002.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-002.jpg" },
                { name: "NPX-003.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-003.jpg" },
                { name: "NPX-004.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-004.jpg" },
                { name: "NPX-005.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-005.jpg" },
                { name: "NPX-006.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-006.jpg" },
                { name: "NPX-007.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-007.jpg" },
                { name: "NPX-008.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-008.jpg" },
                { name: "NPX-009.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-009.jpg" },
                { name: "NPX-010.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-010.jpg" },
                { name: "NPX-011.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-011.jpg" },
                { name: "NPX-012.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-012.jpg" },
                { name: "NPX-013.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-013.jpg" },
                { name: "NPX-014.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-014.jpg" },
                { name: "NPX-015.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-015.jpg" },
                { name: "NPX-016.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-016.jpg" },
                { name: "NPX-017.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-017.jpg" },
                { name: "NPX-018.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-018.jpg" },
                { name: "NPX-019.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-019.jpg" },
                { name: "NPX-020.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-020.jpg" },
                { name: "NPX-021.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-021.jpg" },
                { name: "NPX-022.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-022.jpg" },
                { name: "NPX-023.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-023.jpg" },
                { name: "NPX-024.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-024.jpg" },
                { name: "NPX-025.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-025.jpg" },
                { name: "NPX-026.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-026.jpg" },
                { name: "NPX-027.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-027.jpg" },
                { name: "NPX-028.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-028.jpg" },
                { name: "NPX-029.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-029.jpg" },
                { name: "NPX-030.jpg", type: "file", path: "assets/samples/Healthy Control/NPX-030.jpg" }
            ]
        },
        {
            name: "Meningioma Tumor",
            type: "folder",
            children: [
                { name: "NPX-001.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-001.jpg" },
                { name: "NPX-002.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-002.jpg" },
                { name: "NPX-003.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-003.jpg" },
                { name: "NPX-004.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-004.jpg" },
                { name: "NPX-005.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-005.jpg" },
                { name: "NPX-006.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-006.jpg" },
                { name: "NPX-007.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-007.jpg" },
                { name: "NPX-008.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-008.jpg" },
                { name: "NPX-009.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-009.jpg" },
                { name: "NPX-010.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-010.jpg" },
                { name: "NPX-011.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-011.jpg" },
                { name: "NPX-012.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-012.jpg" },
                { name: "NPX-013.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-013.jpg" },
                { name: "NPX-014.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-014.jpg" },
                { name: "NPX-015.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-015.jpg" },
                { name: "NPX-016.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-016.jpg" },
                { name: "NPX-017.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-017.jpg" },
                { name: "NPX-018.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-018.jpg" },
                { name: "NPX-019.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-019.jpg" },
                { name: "NPX-020.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-020.jpg" },
                { name: "NPX-021.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-021.jpg" },
                { name: "NPX-022.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-022.jpg" },
                { name: "NPX-023.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-023.jpg" },
                { name: "NPX-024.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-024.jpg" },
                { name: "NPX-025.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-025.jpg" },
                { name: "NPX-026.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-026.jpg" },
                { name: "NPX-027.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-027.jpg" },
                { name: "NPX-028.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-028.jpg" },
                { name: "NPX-029.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-029.jpg" },
                { name: "NPX-030.jpg", type: "file", path: "assets/samples/Meningioma Tumor/NPX-030.jpg" }
            ]
        },
        {
            name: "Pituitary Tumor",
            type: "folder",
            children: [
                { name: "NPX-001.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-001.jpg" },
                { name: "NPX-002.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-002.jpg" },
                { name: "NPX-003.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-003.jpg" },
                { name: "NPX-004.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-004.jpg" },
                { name: "NPX-005.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-005.jpg" },
                { name: "NPX-006.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-006.jpg" },
                { name: "NPX-007.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-007.jpg" },
                { name: "NPX-008.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-008.jpg" },
                { name: "NPX-009.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-009.jpg" },
                { name: "NPX-010.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-010.jpg" },
                { name: "NPX-011.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-011.jpg" },
                { name: "NPX-012.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-012.jpg" },
                { name: "NPX-013.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-013.jpg" },
                { name: "NPX-014.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-014.jpg" },
                { name: "NPX-015.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-015.jpg" },
                { name: "NPX-016.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-016.jpg" },
                { name: "NPX-017.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-017.jpg" },
                { name: "NPX-018.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-018.jpg" },
                { name: "NPX-019.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-019.jpg" },
                { name: "NPX-020.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-020.jpg" },
                { name: "NPX-021.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-021.jpg" },
                { name: "NPX-022.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-022.jpg" },
                { name: "NPX-023.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-023.jpg" },
                { name: "NPX-024.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-024.jpg" },
                { name: "NPX-025.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-025.jpg" },
                { name: "NPX-026.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-026.jpg" },
                { name: "NPX-027.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-027.jpg" },
                { name: "NPX-028.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-028.jpg" },
                { name: "NPX-029.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-029.jpg" },
                { name: "NPX-030.jpg", type: "file", path: "assets/samples/Pituitary Tumor/NPX-030.jpg" }
            ]
        }
    ]
};
